kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: hipster-shop
  name: account-otel-demo-manager

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: hipster-shop
  name: role-otel-demo-manager
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups:
      - chaos-mesh.org
    resources: [ "*" ]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-otel-demo-manager
  namespace: hipster-shop
subjects:
  - kind: ServiceAccount
    name: account-otel-demo-manager
    namespace: hipster-shop
roleRef:
  kind: Role
  name: role-otel-demo-manager
  apiGroup: rbac.authorization.k8s.io
