kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: otel-demo
  name: account-otel-demo-viewer

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: otel-demo
  name: role-otel-demo-viewer
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups:
      - chaos-mesh.org
    resources: [ "*" ]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-otel-demo-viewer
  namespace: otel-demo
subjects:
  - kind: ServiceAccount
    name: account-otel-demo-viewer
    namespace: otel-demo
roleRef:
  kind: Role
  name: role-otel-demo-viewer
  apiGroup: rbac.authorization.k8s.io
