apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otelcollector-servicemon
  labels:
    release: prometheus
spec:
  endpoints:
    - interval: 5s
      port: prometheus
  selector:
    matchLabels:
      app.kubernetes.io/name: oteld-collector