apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: oteld
spec:
  mode: daemonset
  hostNetwork: true
  serviceAccount: otelcontribcol
  image: otel/opentelemetry-collector-contrib:0.72.0
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      zipkin:
        endpoint: 0.0.0.0:9411

      otlp/spanmetrics:
        protocols:
          grpc:
            endpoint: "localhost:65535"

      otlp/servicegraph: # Dummy receiver for the metrics pipeline
         protocols:
           grpc:
             endpoint: localhost:12345

    processors:
      batch:
        send_batch_max_size: 1000
        timeout: 30s
        send_batch_size : 800

      servicegraph:
        metrics_exporter: prometheus # Exporter to send metrics to
        latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms] # Buckets for latency histogram
        dimensions: [cluster, namespace] # Additional dimensions (labels) to be added to the metrics extracted from the resource and span attributes
        store: # Configuration for the in-memory store
          ttl: 2s # Value to wait for an edge to be completed
          max_items: 200 # Amount of edges that will be stored in the storeMap

      spanmetrics:
        metrics_exporter: prometheus

      memory_limiter:
        check_interval: 1s
        limit_percentage: 70
        spike_limit_percentage: 30

      k8sattributes:
        auth_type: serviceAccount
        passthrough: false
        filter:
          node_from_env_var: K8S_NODE_NAME
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time

    exporters:
      logging:
      otlp:
        endpoint: TEMPO_TO_REPLACE.tempo.svc:4317
        tls:
          insecure: true

      prometheus:
        endpoint: "0.0.0.0:9090"
        namespace: default

      otlp/spanmetrics:
          endpoint: "localhost:55677"
          tls:
            insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp,zipkin]
          processors: [memory_limiter,k8sattributes,spanmetrics,servicegraph,batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter,k8sattributes,batch]
          exporters: [prometheus]
        metrics/spanmetrics:
          receivers: [otlp/spanmetrics]
          exporters: [otlp/spanmetrics]
        metrics/servicegraph:
          receivers: [otlp/servicegraph]
          processors: []
          exporters: [prometheus]