apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: loki-output
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  match: kube.*
  loki:
    autoKubernetesLabels: "on"
    host: LOKI_SERVICE_TOREPLACE.loki.svc.cluster.local
    port: 80
